services:
  db:
    container_name: mongodb_datawarehouse
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=datawarehouse
      - MONGO_INITDB_ROOT_PASSWORD=123
    restart: unless-stopped